rss_urls = {}

rss_urls["http://www.ilo.org/global/rss-feeds/news/lang--en/index.htm"]='ILO'
rss_urls["http://www.etui.org/layout/set/rss/content/view/rss_full/877"]='ETUI'
rss_urls["http://www.loc.gov/law/foreign-news/feed/"]='LOC'

rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/US.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/World.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Business.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Science.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Environment.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Health.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Research.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Arts.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Books.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Movies.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Music.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml"]='NYT'
rss_urls["http://rss.nytimes.com/services/xml/rss/nyt/Travel.xml"]='NYT'

rss_urls["http://feeds.washingtonpost.com/rss/politics"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/opinions"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/local"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/national"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/world"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/business"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/lifestyle"]='WP'
rss_urls["http://feeds.washingtonpost.com/rss/entertainment"]='WP'

rss_urls["http://feeds.bbci.co.uk/news/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/uk/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/business/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/health/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/science_and_environment/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/technology/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/technology/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/asia/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/europe/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/latin_america/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/middle_east/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/england/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/northern_ireland/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/scotland/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/wales/rss.xml"]='BBC'
rss_urls["http://feeds.bbci.co.uk/news/world/africa/rss.xml"]='BBC'


rss_urls["http://www.cnbc.com/id/100003114/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/15837362/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/100727362/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10000664/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/19794221/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/19832390/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10001147/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/20910258/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10000113/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/19854910/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10000108/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10000115/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10001054/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10000101/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/10000116/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/19836768/device/rss/rss.html"]='CNBC'
rss_urls["http://www.cnbc.com/id/44877279/device/rss/rss.html"]='CNBC'

rss_urls["https://www.theguardian.com/world/rss"]='Guardian'
rss_urls["https://www.theguardian.com/uk/environment/rss"]='Guardian'
rss_urls["https://www.theguardian.com/uk/technology/rss"]='Guardian'
rss_urls["https://www.theguardian.com/uk/business/rss"]='Guardian'
rss_urls["https://www.theguardian.com/uk-news/rss"]='Guardian'
rss_urls["https://www.theguardian.com/uk/culture/rss"]='Guardian'
rss_urls["https://www.theguardian.com/fashion/rss"]='Guardian'
#rss_urls[""]=''


